CREATE DATABASE CNPM_DB
GO
-----------------------
USE CNPM_DB
GO
-----------------------
CREATE TABLE DONVITINH(
	MADONVITINH VARCHAR(10) NOT NULL,
	TENDONVITINH VARCHAR(255) NOT NULL,
	PRIMARY KEY (MADONVITINH)
);

CREATE TABLE LOAISANPHAM(
	MALOAISANPHAM VARCHAR(10) NOT NULL,
	TENLOAISANPHAM VARCHAR(25) NOT NULL,
	MADONVITINH VARCHAR(10) NOT NULL,
	LOAIDA VARCHAR(50) NOT NULL,
	HANG VARCHAR(50) NOT NULL,
	CHATLIEU VARCHAR(50) NOT NULL,
	TRONGLUONG DECIMAL(15,2) NOT NULL,
	LOINHUAN DECIMAL(15,2),
	PRIMARY KEY (MALOAISANPHAM),
	FOREIGN KEY (MADONVITINH) REFERENCES DONVITINH(MADONVITINH)
);

CREATE TABLE SANPHAM(
	MASANPHAM VARCHAR(10) NOT NULL,
	TENSP VARCHAR(255) NOT NULL,
	MALOAISANPHAM VARCHAR(10) NOT NULL,
	DONGIABAN DECIMAL(10,2),
	DONGIAMUA DECIMAL(15,2),
	SOLUONGTON INTEGER,
	PRIMARY KEY (MASANPHAM),
	FOREIGN KEY (MALOAISANPHAM) REFERENCES LOAISANPHAM(MALOAISANPHAM)
);

CREATE TABLE BAOCAOTON(
	MABAOCAO VARCHAR(10) NOT NULL,
	NGAYLAPBAOCAO DATE NOT NULL,
	MASANPHAM VARCHAR(10) NOT NULL,
	TONDAU INT,
	TONCUOI INT,
	SOLUONGMUAVAO DECIMAL(15,2),
	SOLUONGBANRA DECIMAL(15,2),
	LOINHUAN DECIMAL(15,2),
	PRIMARY KEY (MABAOCAO),
	FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
)

CREATE TABLE KHACHHANG(
	MAKHACHHANG VARCHAR(10) NOT NULL,
	TENKH VARCHAR(255) NOT NULL,
	DIACHI VARCHAR(255) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PRIMARY KEY (MAKHACHHANG)
)

CREATE TABLE PHIEUBANHANG(
	SOPHIEUBANHANG VARCHAR(10) NOT NULL,
	MAKHACHHANG VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL,
	TONGTIEN DECIMAL(15,2)
	PRIMARY KEY (SOPHIEUBANHANG),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)	

CREATE TABLE CT_PHIEUBANHANG(
	SOPHIEUBANHANG VARCHAR(10) NOT NULL,
	MASANPHAM VARCHAR(10) NOT NULL,
	SOLUONGBAN INT NOT NULL,
	DONGIABAN DECIMAL(15,2) NOT NULL,
	THANHTIEN DECIMAL(15,2)
	PRIMARY KEY (SOPHIEUBANHANG, MASANPHAM),
	FOREIGN KEY (SOPHIEUBANHANG) REFERENCES PHIEUBANHANG(SOPHIEUBANHANG),
	FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
)

CREATE TABLE PHIEUMUAHANG(
	SOPHIEUMUAHANG VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL,
	SOLUONG INT,
	MASANPHAM VARCHAR(10) NOT NULL,
	PRIMARY KEY (SOPHIEUMUAHANG),
	FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
)

CREATE TABLE CT_PHIEUMUAHANG(
	SOPHIEUMUAHANG VARCHAR(10) NOT NULL,
	MAKHACHHANG VARCHAR(10) NOT NULL,
	SOLUONGMUA INT,
	DONGIAMUA DECIMAL(15,2),
	THANHTIEN DECIMAL(15,2)
	PRIMARY KEY (SOPHIEUMUAHANG, MAKHACHHANG),
	FOREIGN KEY (SOPHIEUMUAHANG) REFERENCES PHIEUMUAHANG(SOPHIEUMUAHANG),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)

CREATE TABLE PHIEUDICHVU(
	SOPHIEUDICHVU VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL,
	TONGTIEN DECIMAL(15,2) NOT NULL,
	TINHTRANG VARCHAR(20),
	SOTIENCONLAI DECIMAL(15,2),
	SOTIENTRATRUOC DECIMAL(15,2),
	MAKHACHHANG VARCHAR(10) NOT NULL,
	PRIMARY KEY (SOPHIEUDICHVU),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
)

CREATE TABLE DICHVU(
	MALOAIDICHVU VARCHAR(10) NOT NULL,
	TENDICHVU VARCHAR(50) NOT NULL,
	DONGIA DECIMAL(15,2) NOT NULL,
	PRIMARY KEY (MALOAIDICHVU)
)

CREATE TABLE CT_PHIEUDICHVU(
	SOPHIEUDICHVU VARCHAR(10) NOT NULL,
	MALOAIDICHVU VARCHAR(10) NOT NULL,
	DONGIADICHVU DECIMAL(15,2) NOT NULL,
	DONGIADUOCTINH DECIMAL(15,2) NOT NULL,
	SOLUONG INT,
	THANHTIEN DECIMAL(15,2) NOT NULL,
	TRATRUOC DECIMAL(15,2),
	CONLAI DECIMAL(15,2),
	NGAYGIAO DATE,
	TINHTRANG VARCHAR(20)
	PRIMARY KEY (SOPHIEUDICHVU, MALOAIDICHVU),
	FOREIGN KEY (SOPHIEUDICHVU) REFERENCES PHIEUDICHVU(SOPHIEUDICHVU),
	FOREIGN KEY (MALOAIDICHVU) REFERENCES DICHVU(MALOAIDICHVU)
)